[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  autocmd VimEnter * execute 'NERDTree'
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
  map <Space>l <Plug>(easymotion-lineforward)
  map <Space>j <Plug>(easymotion-j)
  map <Space>k <Plug>(easymotion-k)
  map <Space>h <Plug>(easymotion-linebackward)
  map <Space>w <Plug>(easymotion-bd-f)
  map <Space>q <Plug>(easymotion-overwin-f)
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
'''

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo = 'previm/previm'
on_ft = ['markdown']
hook_add = '''
  autocmd BufRead,BufNewFile *.md  set filetype=markdown
  nnoremap <silent> <C-p> :PrevimOpen<CR>
  let g:vim_markdown_folding_disabled=1
  let g:previm_enable_realtime=1
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
on_ft = ['markdown']

[[plugins]]
repo = 'godlygeek/tabular'
on_ft = ['markdown']

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
  let g:molokai_original = 1
  let g:rehash256 = 1
  let g:airline#extensions#tabline#enabled = 1
  let g:airline_powerline_fonts = 1
  nmap <C-q> <Plug>AirlineSelectPrevTab
  nmap <C-> <Plug>AirlineSelectNextTab
  let g:airline#extensions#tabline#buffer_idx_mode = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_i = 1
hook_source = '''
  let g:prettier#autoformat = 0
  let g:prettier#quickfix_enabled = 0
  autocmd BufWritePre *.js,*.css,*.html,*.php,*.ruby,*.md,*.vue PrettierAsync
'''

[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
  let g:ale_lint_on_save = 1
  let g:ale_lint_on_text_changed = 0
  let g:ale_lint_on_enter = 0
  let g:ale_lint_on_text_changed = 1
  let g:ale_sign_column_always = 1
  let g:ale_sign_error = ''
  let g:ale_sign_warning = ''
  let g:ale_linters = {
  \   'javascript': ['eslint'],
  \   'css': ['stylelint'],
  \}
'''
