[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    map <Space>l <Plug>(easymotion-lineforward)
    map <Space>j <Plug>(easymotion-j)
    map <Space>k <Plug>(easymotion-k)
    map <Space>h <Plug>(easymotion-linebackward)
    map <Space>w <Plug>(easymotion-bd-f)
    map <Space>q <Plug>(easymotion-overwin-f)
'''

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'bronson/vim-trailing-whitespace'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = 'jwalton512/vim-blade'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'simeji/winresizer'

[[plugins]]
repo = 'prettier/vim-prettier'
build = 'npm install'
on_ft = ['javascript','css','html','php','ruby','markdown','vue']
hook_source = '''
  let g:prettier#autoformat = 0
  let g:prettier#quickfix_enabled = 0
  autocmd BufWritePre *.js,*.css,*.html,*.php,*.ruby,*.md,*.vue PrettierAsync
'''
